#!/bin/bash
var_proxy=http://192.168.49.1:8282/

if [[ $1 == "off" ]]; then
  unset http_proxy
  unset https_proxy
  unset NO_PROXY

  git config --global --unset http.proxy
  git config --global --unset https.proxy

  npm config rm proxy &>/dev/null

  sudo rm -rf /etc/apt/apt.conf.d/proxy.conf
elif [[ $1 == "status" ]]; then
  if [[ -e /etc/apt/apt.conf.d/proxy.conf ]]; then
    echo "Proxy Aktif!"
  else
    echo "Proxy Sudah Mati"
  fi
else
  export http_proxy="$var_proxy"
  export https_proxy="$var_proxy"
  export NO_PROXY=localhost,127.0.0.1,::1

  git config --global http.proxy $var_proxy
  git config --global https.proxy $var_proxy

  npm config set proxy $var_proxy &>/dev/null

  cat >proxy.conf <<EOF
Acquire::http::Proxy "$var_proxy";
Acquire::https::Proxy "$var_proxy";
EOF

  sudo mv proxy.conf /etc/apt/apt.conf.d/proxy.conf
fi
