#!/bin/bash
flproxy=/etc/ipproxy
red=$(tput setaf 1)
gren=$(tput setaf 2)
yellow=$(tput setaf 3)

msg() {
  local colors="/etc/new-adm-color"
  if [[ ! -e $colors ]]; then
    COLOR[0]='\033[1;37m' #BRAN='\033[1;37m'
    COLOR[1]='\e[31m'     #VERMELHO='\e[31m'
    COLOR[2]='\e[32m'     #VERDE='\e[32m'
    COLOR[3]='\e[33m'     #AMARELO='\e[33m'
    COLOR[4]='\e[34m'     #AZUL='\e[34m'
    COLOR[5]='\e[35m'     #MAGENTA='\e[35m'
    COLOR[6]='\033[1;36m' #MAG='\033[1;36m'
  else
    local COL=0
    for number in $(cat $colors); do
      case $number in
      1) COLOR[$COL]='\033[1;37m' ;;
      2) COLOR[$COL]='\e[31m' ;;
      3) COLOR[$COL]='\e[32m' ;;
      4) COLOR[$COL]='\e[33m' ;;
      5) COLOR[$COL]='\e[34m' ;;
      6) COLOR[$COL]='\e[35m' ;;
      7) COLOR[$COL]='\033[1;36m' ;;
      esac
      let COL++
    done
  fi
  NEGRITO='\e[1m'
  SEMCOR='\e[0m'
  case $1 in
  -ne) cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
  -ama) cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -verm) cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -verm2) cor="${COLOR[1]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -azu) cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -verd) cor="${COLOR[2]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -bra) cor="${COLOR[0]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -garis) cor="${COLOR[0]}${NEGRITO}" && echo -e "======= ${cor}${2}${SEMCOR} =======" ;;
  "-bar2" | "-bar") cor="${COLOR[4]}======================================================" && echo -e "${SEMCOR}${cor}${SEMCOR}" ;;
  esac
}

if [[ "${EUID}" -ne 0 ]]; then
  msg -verm "Kamu harus jalankan script ini mode root"
  exit 1
fi

[[ ! -e ${flproxy} ]] && {
  msg -bra "1. Format Input IP Proxy"
  msg -ama "PROTOKOL =>"
  msg -ama "  - http / https / ftp / ftps / socks"
  msg -ama "=> PROTOKOL://IP:PORT"
  msg -ama "=> PROTOKOL://USER:PASSWORD@IP:PORT"
  read -rp "$(msg -verd "Masukkan IP Proxy"): " opsi
  echo $opsi >$flproxy &>/dev/null
  touch ${flproxy} &>/dev/null
}
var_proxy=$(cat ${flproxy} &>/dev/null)

if [[ $1 == "off" ]]; then
  msg -bar
  msg -garis "Sedang hapus Environment"
  unset http_proxy
  unset https_proxy
  unset NO_PROXY

  msg -garis "Sedang hapus proxy di GIT"
  git config --global --unset http.proxy
  git config --global --unset https.proxy

  msg -garis "Sedang hapus proxy di NPM"
  npm config rm proxy &>/dev/null
  npm config rm http-proxy &>/dev/null
  npm config rm https-proxy &>/dev/null

  msg -garis "Sedang hapus proxy di APT"
  msg -bar
  sudo rm -rf /etc/apt/apt.conf.d/proxy.conf

elif [[ $1 == "status" ]]; then

  if [[ -e /etc/apt/apt.conf.d/proxy.conf ]]; then
    msg -ama "PROXY Aktif!"
  else
    msg -ama "PROXY Mati!"
  fi

elif [[ $1 == "on" ]]; then
  msg -bar
  msg -garis "Membuat proxy di Environment"
  export http_proxy="$var_proxy"
  export https_proxy="$var_proxy"
  export NO_PROXY=localhost,127.0.0.1,::1

  msg -garis "Membuat proxy di GIT"
  git config --global http.proxy $var_proxy
  git config --global https.proxy $var_proxy

  msg -garis "Membuat proxy di NPM"
  npm config set proxy $var_proxy &>/dev/null
  npm config set http-proxy $var_proxy &>/dev/null
  npm config set https-proxy $var_proxy &>/dev/null

  msg -garis "Membuat proxy di APT"
  cat >proxy.conf <<EOF
Acquire::http::Proxy "$var_proxy";
Acquire::https::Proxy "$var_proxy";
EOF
  sudo mv proxy.conf /etc/apt/apt.conf.d/proxy.conf
  msg -bar

elif [[ $1 == "edit" ]]; then
  echo $2 >$flproxy
else
  msg -bar
  msg -ama "Tool konfigurasi proxy otomatis"
  msg -bar
  msg -azu "========= Tutorial ========="
  msg -bra "1. Format Input IP Proxy"
  msg -ama "PROTOKOL =>"
  msg -ama "  - http / https / ftp / ftps / socks"
  msg -ama "=> PROTOKOL://IP:PORT"
  msg -ama "=> PROTOKOL://USER:PASSWORD@IP:PORT"
  msg -bra "2. Edit IP Proxy"
  msg -ama "==> sudo proxy edit FormatIPProxy"
  msg -bra "3. Menghidupkan proxy"
  msg -ama "==> sudo proxy on"
  msg -bra "4. Mematikan proxy"
  msg -ama "==> sudo proxy off"
  msg -bra "5. Melihat proxy mati atau hidup"
  msg -ama "==> sudo proxy status"
  msg -bra "6. Menghidupkan proxy pada visual code"
  msg -ama "- Buka setting"
  msg -ama "- Cari = proxy"
  msg -ama "- Matikan √ pada Http: Proxy Strict SSL"
  msg -ama "- Pada Http: Proxy Support => override"
  msg -ama "- Pada Http: Proxy => isi proxy kalian"
  msg -bar
fi
